version: '2'
services:
  ssclient:
    build:
      context: ss-client/.
    ports:
    - 1080:1080
    command: "-c /etc/sslocal.json"
  hao-privoxy:
    build:
      context: privoxy/.
    ports:
     - 2080:2080
    depends_on:
    - ssclient